spring:
  datasource:
    url: jdbc:mysql://icuas-mysql:3306/medical_alerts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: medical_user
    password: medical_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

medical:
  alerts:
    evaluation-interval: 3000

logging:
  level:
    com.medical.alerts: DEBUG
    org.hibernate.SQL: DEBUG